### ISSUE TITLE
tinyxml_vendor causes nightly clang libcxx build failure

### ISSUE THREAD

**Issue by dabonnie** [ros2/tinyxml_vendor#15]
The [nightly clang libcxx build](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/) is currently failing with the following [output](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/325/console#console-section-1):

```
--- stderr: tinyxml_vendor
23:57:00 CMake Error at tinyxml-2.6.2-stamp/download-tinyxml-2.6.2.cmake:157 (message):
23:57:00   Each download failed!
23:57:00 
23:57:00     error: downloading 'https://superb-dca2.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz' failed
23:57:00          status_code: 7
23:57:00          status_string: "Couldn't connect to server"
23:57:00          log:
23:57:00          --- LOG BEGIN ---
23:57:00            Trying 209.61.193.20...
23:57:00 
23:57:00   TCP_NODELAY set
23:57:00 
23:57:00   connect to 209.61.193.20 port 443 failed: Connection timed out
23:57:00 
23:57:00   Failed to connect to superb-dca2.dl.sourceforge.net port 443: Connection
23:57:00   timed out
23:57:00 
23:57:00   Closing connection 0
23:57:00 
23:57:00   
23:57:00 
23:57:00          --- LOG END ---
....
```

I've been able to reproduce this error outside of the buildfarm (Ubuntu 18.04, building ros2 master from source).

**Comment by emersonknapp** [comment]
Is the reason that this is not failing on other platforms because it's installed via apt/brew/(windows-thing?) and never hits the vendor library portion? 

Not a good sign that this unrelated build is what reveals that issue, yikes!

I can reproduce by trying 
```
wget https://superb-dca2.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz
```

The connection is not there

**Comment by emersonknapp** [comment]
The issue seems to be a no longer existing mirror `superb-dca2.dl.sourceforge.net` - the direct link 
https://downloads.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz works fine right now
