### ISSUE TITLE
tinyxml_vendor doesn't handle config style packages.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/tinyxml_vendor#2]
While trying to set up system-resolvable dependencies on Windows. I found that the tinyxml_vendor package has no support for locating packages entered into the CMake system or user registries on Windows.

I've been troubleshooting this by building https://github.com/ros2/urdfdom locally.

I don't yet have a full ament toolchain up and running on Windows so I'm running cmake commands by hand but still able to exhibit the same failure mode as [example CI jobs](http://ci.ros2.org/job/ci_windows/2354/consoleText).

#### What (I think) is happening currently

tinyxml_vendor is getting built.
[This line](https://gist.github.com/nuclearsandwich/583938a6b5d2a5002973b2c9223e466b#file-20_installing_ament_cmake_export_libraries-txt-L97) in the output corresponds to [this message](https://github.com/nuclearsandwich/tinyxml_vendor/blob/14cc21efd787ff49e1c51bfdee4a5a85cd2f6db7/CMakeLists.txt#L26) printed when a system installed cmake is found. In the case of this specific build, the system package is only found because of a second `find_package(TinyXML)` that explicitly looks for Config packages. Which was [added](https://github.com/nuclearsandwich/tinyxml_vendor/commit/14cc21efd787ff49e1c51bfdee4a5a85cd2f6db7) in my fork after testing on Windows. The reason why the simple find_package command, which according to documentation should look first for module packages and then for config packages, does not appear to look for config packages is unknown to me.

Because tinyxml_vendor found a suitable system TinyXML package, it doesn't download and build tinyxml from source. This is what we want. However, the tinyxml_vendor package does install itself, and its Config file [adds its `FindTinyXML.cmake` to the current CMAKE_MODULE_PATH](https://github.com/ros2/tinyxml_vendor/blob/49e87bcbcf6e8e763fc05164af6cb41453f7fe32/tinyxml_vendorConfig.cmake.in#L12-L13) under the previously correct assumption that `FindTinyXML.cmake` was how the system tinyxml package was found.

When a package attempts to build against TinyXML a cmake error is thrown when the `find_package(TinyXML)` command fails.

#### What should happen

When the system package is found, it should be discoverable again during later builds even with tinyxml_vendor installed as a find module.

#### Thoughts on what we could do to resolve this

- Unless there's a specific reason we _do not_ want to accept Config packages, we should figure out why find_package isn't finding them and see if that resolves our issue.

- If we do need to explicitly request find_package look for Config packages every time, should that be something we bake into the find module so that projects downstream need only require tinyxml_vendor and avoid that logic?

- If a system package is found via find_package in config mode or module mode, it should be used.

- If the Find-module fails during tinyxml_vendor build time and a system package is found, should we even register the find module? I have no technical grounding for this claim but it almost seems as if the find module is interfering with config file package resolution. When building test packages that look directly for TinyXML without involving tinyxml_vendor at all, the package is found without issue. (The [eigen-test](https://github.com/nuclearsandwich/eigen-test) repo is an example of this, which [builds on CI](http://ci.ros2.org/job/ci_windows/2342/consoleFull).

cc @Karsten1987 because these configuration issues are blocking his work and @dirk-thomas for his expertise with cmake and the vendor packages.

**Comment by dirk-thomas** [comment]
The [CMake docs](https://cmake.org/cmake/help/v3.5/command/find_package.html) clearly mentions the order in which modules and configs are being consider:

> If no module is found and the MODULE option is not given the command proceeds to Config mode.

**Comment by nuclearsandwich** [comment]
> The CMake docs clearly mentions the order in which modules and configs are being consider:
> 
> >     If no module is found and the MODULE option is not given the command proceeds to Config mode.

I'd found that but interpreted it as CMake would prefer find modules but fallback to config if the find module doesn't find the package. Does it actually mean that if a FindTinyXML.cmake file is found but doesn't succeed that it doesn't even try to find a config package?

**Comment by dirk-thomas** [comment]
I haven't tried that case. It could be either or. Maybe try it out to make sure.

**Comment by nuclearsandwich** [comment]
> I haven't tried that case. It could be either or. Maybe try it out to make sure.

Based on the empirical testing that prompted this issue, it appears that if a Find<Package>.cmake is present and doesn't find the package, the find_package command does not then attempt to use the package registry.

A later `find_package` command with an explicit CONFIG directive will find the package. As will a plain `find_package` command when tinyxml_vendor's FindTinyXML.cmake is not present on the CMAKE_MODULE_PATH.
