### ISSUE TITLE
tinyxml: Couldn't connect to server

### ISSUE THREAD

**Issue by pokitoz** [ros2/tinyxml_vendor#8]
Hello,

I got this issue yesterday and today when building tinyxml. I guess the link is down and maybe you will have to find another url to get the tar.gz

CMake Error at tinyxml-2.6.2-stamp/download-tinyxml-2.6.2.cmake:27 (message):
  error: downloading
  'https://superb-dca2.dl.sourceforge.net/project/tinyxml/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz'
  failed
    status_code: 7
    status_string: "Couldn't connect to server"
    log:   Trying 209.61.193.20...
  connect to 209.61.193.20 port 443 failed: Connection timed out
  Failed to connect to superb-dca2.dl.sourceforge.net port 443: Connection
  timed out
  Closing connection 0

I did an upload on my dropbox and changed the url to fix this issue.

**Comment by nuclearsandwich** [comment]
Should we upload a copy of this binary as a release artifact on this repository and link to it so that we're resilient against mirror changes?

**Comment by wjwwood** [comment]
> Should we upload a copy of this binary as a release artifact on this repository and link to it so that we're resilient against mirror changes?

Sounds fine to me.

**Comment by dirk-thomas** [comment]
Currently the download seems to be using a URL of one specific mirror. Maybe switching to a mirror-independent link will already make it work. If that is the case I would prefer that over hosting the file "ourselves".

**Comment by dirk-thomas** [comment]
I am going to close this since this seems to have been a one-time problem. Please feel free to comment if this happens again.
